// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``` 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAviiGDIRFA9O1CrzaijtFUrDvJXdYXEQ',
    appId: '1:259434368076:web:4fec9006b618e0250af8e9',
    messagingSenderId: '259434368076',
    projectId: 'spotify1327',
    authDomain: 'spotify1327.firebaseapp.com',
    databaseURL: 'https://spotify1327-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify1327.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfPAiV7TpH2QRyWeXrJziV9vG7pV8f10',
    appId: '1:259434368076:android:f38bda17aa0d67500af8e9',
    messagingSenderId: '259434368076',
    projectId: 'spotify1327',
    databaseURL: 'https://spotify1327-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify1327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ8WIY5yBexHSD_6d4nnolsHrUn0M8G3A',
    appId: '1:259434368076:ios:98496501c538eaa20af8e9',
    messagingSenderId: '259434368076',
    projectId: 'spotify1327',
    databaseURL: 'https://spotify1327-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify1327.appspot.com',
    iosBundleId: 'com.itsmohsin.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ8WIY5yBexHSD_6d4nnolsHrUn0M8G3A',
    appId: '1:259434368076:ios:98496501c538eaa20af8e9',
    messagingSenderId: '259434368076',
    projectId: 'spotify1327',
    databaseURL: 'https://spotify1327-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify1327.appspot.com',
    iosBundleId: 'com.itsmohsin.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAviiGDIRFA9O1CrzaijtFUrDvJXdYXEQ',
    appId: '1:259434368076:web:07be571c28b5935b0af8e9',
    messagingSenderId: '259434368076',
    projectId: 'spotify1327',
    authDomain: 'spotify1327.firebaseapp.com',
    databaseURL: 'https://spotify1327-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotify1327.appspot.com',
  );
}
